DROP TABLE IF EXISTS user;
DROP TABLE IF EXISTS location;


CREATE TABLE user (
    userId INTEGER UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR UNIQUE,
    password VARCHAR
);

CREATE TABLE location (
	id INTEGER UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	userId INTEGER UNSIGNED,
    deviceName VARCHAR,
    latitude INTEGER,
    longitude INTEGER,
    FOREIGN KEY (userId) REFERENCES user(userId)
);
